import React, { useEffect, useRef, useState } from 'react';
import { createRoot } from 'react-dom/client';
import { ArrowUpRight, ArrowRight, ArrowDown, Download, MapPin, Menu, X, Database, Network, Layers, BrainCircuit, BarChart3, Code2, Mail, Copy, Check, Sparkles, GitBranch, Sun, Moon } from 'lucide-react';
import './style.css';
import './themes.css';
import { PreferencesProvider, usePreferences } from './i18n';

const skills = [
  { name: 'Data engineering', icon: Database, items: ['Python','SQL','ETL / ELT','Apache NiFi','Airbyte','Docker','Data Warehouse','SQL Server','MongoDB','Pandas','Big Data'] },
  { name: 'AI & machine learning', icon: BrainCircuit, items: ['Machine Learning','Deep Learning','CNN','NLP','LLM','AI Agents'] },
  { name: 'Data & analytics', icon: BarChart3, items: ['Power BI','Tableau','Data Quality','Data Governance','Data Analysis'] },
  { name: 'Software development', icon: Code2, items: ['React','FastAPI','JavaScript','HTML','CSS','REST APIs','SQLAlchemy'] },
];
const projects = [
  { title: 'Data Pipeline Engineering', category: 'Data engineering', desc: 'Connecting data. Automating the flow.', detail: 'Design of an automated ETL pipeline using Apache NiFi and Airbyte, integrating SQL Server, MongoDB and Docker for data workflow automation and management.', tags: ['Apache NiFi','Airbyte','Docker','SQL Server','MongoDB'], icon: GitBranch, visual: 'pipeline' },
  { title: 'Multi-cloud Federation', category: 'Data engineering', desc: 'Multiple sources. One perspective.', detail: 'Design of a data virtualization solution for federated queries across multi-cloud sources, with a unified reporting dashboard for decision-making analytics.', tags: ['Data virtualization','Federated queries','Reporting'], icon: Network, visual: 'cloud' },
  { title: 'Image Recognition with CNN', category: 'AI & ML', desc: 'Teaching machines to see patterns.', detail: 'Design of a Deep Learning model based on Convolutional Neural Networks for image classification, with development of a graphical interface.', tags: ['Deep Learning','CNN','Image classification'], icon: BrainCircuit, visual: 'cnn' },
  { title: 'ELT Pipeline', category: 'Data engineering', desc: 'From raw records to connected data.', detail: 'Implementation of an ELT pipeline for integrating, transforming and loading data between relational and NoSQL databases.', tags: ['ELT','Relational databases','NoSQL'], icon: Database, visual: 'elt' },
  { title: 'Emotion Prediction', category: 'AI & ML', desc: 'Predicting emotions from text.', detail: 'Emotion prediction from textual data using Python and Machine Learning, including preprocessing and model evaluation. PFI internship at Expertise Data, August 2025.', tags: ['Python','Machine Learning','NLP'], icon: Sparkles, visual: 'sentiment' },
];
const stages = [
  ['Data ingestion', 'Bring datasets and database records into a shared workflow.', Database],
  ['Data analysis', 'Profile datasets with Python and Pandas to understand their structure.', BarChart3],
  ['Quality checks', 'Identify missing values, inconsistencies and validation issues.', Check],
  ['Business rules', 'Translate domain requirements into executable validation checks.', Code2],
  ['AI / DVIE', 'Explore natural-language rules and explanations with an intelligent assistant.', BrainCircuit],
  ['Reporting', 'Turn verification results into reports and actionable insights.', Layers],
] as const;

function Globe() {
  const { t, theme } = usePreferences();
  const ref = useRef<HTMLCanvasElement>(null);
  useEffect(() => {
    const canvas = ref.current!; const ctx = canvas.getContext('2d'); if (!ctx) return;
    const reduced = matchMedia('(prefers-reduced-motion: reduce)').matches;
    let frame = 0, time = 0; const points = Array.from({length: 700}, (_, i) => { const y = 1 - i / 699 * 2; const r = Math.sqrt(1-y*y); const a = i * 2.399963; return [Math.cos(a)*r,y,Math.sin(a)*r]; });
    const draw = () => { const size = canvas.clientWidth; const dpr = Math.min(devicePixelRatio,2); if(canvas.width !== size*dpr){canvas.width=size*dpr;canvas.height=size*dpr;} ctx.setTransform(dpr,0,0,dpr,0,0);ctx.clearRect(0,0,size,size); const radius=size*.345; time+=.0016;
      const projected = points.map(([x,y,z])=> {const rx=x*Math.cos(time)-z*Math.sin(time);const rz=x*Math.sin(time)+z*Math.cos(time);return [size/2+rx*radius,size/2+y*radius,rz];});
      projected.forEach(([x,y,z],i)=>{const color=theme==='light'?(z>.3?'22,98,131':'55,111,151'):(z>.3?'123,220,239':'66,132,172');ctx.fillStyle=`rgba(${color},${.2+(z+1)*.32})`;ctx.beginPath();ctx.arc(x,y,z>.45?1.35:.8,0,Math.PI*2);ctx.fill();if(i%3===0){const next=projected[(i+21)%points.length];if(Math.hypot(x-next[0],y-next[1])<size*.13){ctx.strokeStyle=`rgba(${theme==='light'?'35,103,138':'70,156,199'},${.03+(z+1)*.045})`;ctx.beginPath();ctx.moveTo(x,y);ctx.lineTo(next[0],next[1]);ctx.stroke();}}});
      if(!reduced)frame=requestAnimationFrame(draw);
    };draw();return()=>cancelAnimationFrame(frame);
  },[theme]);
  return <div className="globe-scene"><div className="orbital orbital-one"/><div className="orbital orbital-two"/><canvas ref={ref} aria-label={t("Animated connected data globe")} role="img"/><span className="float-node node-ai"><BrainCircuit size={17}/>{t(" Artificial intelligence")}</span><span className="float-node node-data"><Database size={17}/>{t(" Data engineering")}</span><span className="float-node node-quality"><Layers size={17}/>{t(" Data quality")}</span><span className="globe-coordinate">33.5731° N &nbsp; 7.5898° W</span><div className="globe-caption"><span className="live-dot"/>{t(" CONNECTING DATA TO POSSIBILITY")}</div></div>;
}
function App(){
  const { t, language, setLanguage, theme, setTheme } = usePreferences();
  const [menu,setMenu]=useState(false),[filter,setFilter]=useState('All projects'),[stage,setStage]=useState(0),[skill,setSkill]=useState(0),[modal,setModal]=useState<string|null>(null),[copied,setCopied]=useState(false);
  const dialog=useRef<HTMLDialogElement>(null);
  useEffect(()=>{if(modal){dialog.current?.showModal();document.body.style.overflow='hidden';}else{dialog.current?.close();document.body.style.overflow='';}return()=>{document.body.style.overflow='';};},[modal]);
  useEffect(()=>{const observer=new IntersectionObserver(entries=>entries.forEach(e=>{if(e.isIntersecting){e.target.classList.add('visible');observer.unobserve(e.target);}}),{threshold:.08});document.querySelectorAll('.reveal').forEach(el=>observer.observe(el));return()=>observer.disconnect();},[]);
  const cv=()=>setModal('cv');
  return <><a className="skip" href="#main">{t("Skip to content")}</a><header><a href="#home" className="brand" aria-label={t("Asmaa Talal home")}>at<span>.</span><span className="brand-name">ASMAA TALAL</span></a><nav className={menu?'open':''} aria-label={t("Main navigation")}>{['About','Internships','Projects','Education'].map(n=><a key={n} onClick={()=>setMenu(false)} href={`#${n.toLowerCase()}`}>{t(n)}</a>)}<a className="nav-contact" onClick={()=>setMenu(false)} href="#contact">{t("Let’s connect ")}<ArrowUpRight size={15}/></a></nav><div className="display-controls" role="group" aria-label={t("Display preferences")}><div className="language-control" role="group" aria-label={t("Language")}><button lang="fr" aria-label="Français" aria-pressed={language==="fr"} onClick={()=>setLanguage("fr")}>FR</button><button lang="en" aria-label="English" aria-pressed={language==="en"} onClick={()=>setLanguage("en")}>EN</button></div><button className="theme-toggle" onClick={()=>setTheme(theme==="dark"?"light":"dark")} aria-label={t(theme==="dark"?"Switch to light mode":"Switch to dark mode")} title={t(theme==="dark"?"Switch to light mode":"Switch to dark mode")}>{theme==="dark"?<Sun size={17}/>:<Moon size={17}/>}</button></div><button className="menu-toggle" aria-label={t("Toggle navigation")} aria-expanded={menu} onClick={()=>setMenu(!menu)}>{menu?<X/>:<Menu/>}</button></header>
  <main id="main"><section className="hero" id="home"><div className="hero-grid"/><div className="hero-copy"><div className="availability"><span className="live-dot"/>{t(" Open to internship opportunities")}</div><p className="eyebrow hero-eyebrow">{t("CURIOUS MIND. DATA-DRIVEN AMBITION.")}</p><h1>Asmaa Talal<span className="accent">.</span></h1><h2>{t("Future Engineer in")}<br/><span>{t("Information Systems")}<br/>& Big Data</span></h2><p className="hero-description">{t("Turning complex data into reliable insights.")}<br/>{t("Building at the intersection of data engineering,")}<br className="desktop-br"/>{t(" artificial intelligence, and intelligent systems.")}</p><div className="hero-actions"><a className="button primary" href="#projects">{t("Explore my work ")}<ArrowUpRight size={17}/></a><button className="button secondary" onClick={cv}><Download size={16}/>{t(" Download CV")}</button></div><div className="hero-location"><MapPin size={14}/>{t(" Casablanca, Morocco ")}<span/> <a href="#contact">{t("Contact me ")}<ArrowUpRight size={13}/></a></div></div><Globe/><a className="scroll-hint" href="#about"><span>{t("SCROLL TO EXPLORE")}</span><ArrowDown size={15}/></a><span className="hero-index">PORTFOLIO / 2026</span></section>
  <div className="discipline-strip">{['DATA ENGINEERING','ARTIFICIAL INTELLIGENCE','BIG DATA','DATA QUALITY'].map(x=><React.Fragment key={x}><span>{t(x)}</span><span className="strip-star">✳</span></React.Fragment>)}</div>
  <section className="section about reveal" id="about"><div><p className="eyebrow">{t("01 / THE PERSON BEHIND THE DATA")}</p><h2>{t("Driven by curiosity.")}<br/>{t("Built on ")}<span className="muted">{t("possibility.")}</span></h2></div><div className="about-profile"><figure className="about-portrait"><img src="./asmaa-talal.png" alt={t("Portrait of Asmaa Talal")} width={1120} height={1404} loading="lazy" decoding="async"/><figcaption>Asmaa Talal<span>{t("Information Systems & Big Data")}</span></figcaption></figure><div className="about-text"><p>{t("I’m Asmaa, an engineering student specializing in ")}<strong>{t("Information Systems & Big Data")}</strong>{t(" at ENSA Berrechid.")}</p><p>{t("I explore how data pipelines, machine learning, and thoughtful software can turn complex information into something useful. During my PFA internship at JAAG Advisory, I completed ")}<strong>DataVex</strong>{t(", an intelligent data quality platform that brings engineering, business rules, and AI together.")}</p><div className="about-foot"><span><span className="live-dot"/>{t(" LEARNING. BUILDING. CONNECTING.")}</span><span>2024 — 2027</span></div></div></div></section>
  <section className="section universe reveal"><div className="section-heading"><div><p className="eyebrow">{t("02 / MY TECHNICAL UNIVERSE")}</p><h2>{t("From raw data to ")}<span className="muted">{t("real insight.")}</span></h2></div><p>{t("A connected approach to intelligent systems.")}<br/>{t("Explore each layer of the workflow.")}</p></div><div className="architecture">{stages.map(([name,,Icon],i)=><React.Fragment key={name}><button className={`architecture-node ${stage===i?'selected':''}`} onClick={()=>setStage(i)} aria-pressed={stage===i}><Icon size={24}/><span className="node-number">0{i+1}</span><strong>{t(name)}</strong></button>{i<5&&<ArrowRight className="connector" size={16}/>}</React.Fragment>)}</div><div className="architecture-detail" aria-live="polite"><span>0{stage+1} / {t(stages[stage][0])}</span><p>{t(stages[stage][1])}</p></div><div className="architecture-base">SQL / NoSQL / APIs <span>→</span>{t(" CONNECTED DATA PLATFORM ")}<span>←</span>{t(" AI / LLM")}</div></section>
  <section className="section internships reveal" id="internships"><div className="section-heading"><div><p className="eyebrow">{t("03 / PROFESSIONAL EXPERIENCE")}</p><h2>{t("Internships & missions")}</h2></div><span className="small-note">{t("LEARNING THROUGH PROFESSIONAL EXPERIENCE")}</span></div><article className="featured"><div className="featured-copy"><span className="feature-label"><span className="live-dot"/>{t(" FEATURED PROJECT ")}<span>2026 / PFA · JAAG Advisory</span></span><span className="project-completed"><Check size={13}/>{t("Completed project")}</span><h3>DataVex<span className="accent">.</span></h3><h4>{t("Better data. Smarter decisions.")}</h4><p>{t("Developed during my PFA internship at JAAG Advisory, DataVex combines AI-powered data quality, business rules and regulatory rules from the EBA taxonomy.")}</p><div className="tags">{['Python','FastAPI','React','SQL Server','AI / LLM','EBA taxonomy'].map(label=><span key={label}>{t(label)}</span>)}</div><button className="button primary" onClick={()=>setModal('DataVex')}>{t("Explore the case study ")}<ArrowUpRight size={17}/></button></div><div className="datavex-visual"><div className="mock-window"><div className="mock-top"><span className="dv-logo">◈</span><strong>DataVex</strong><span className="mock-label">{t("PLATFORM CONCEPT")}</span><div className="window-dots">•••</div></div><div className="mock-body"><div className="mock-sidebar"><Layers size={17}/><Database size={17}/><BarChart3 size={17}/><BrainCircuit size={17}/></div><div className="mock-content"><div className="mock-title">{t("Your data. A clearer picture.")}<span>{t("DATA QUALITY OVERVIEW")}</span></div><div className="mock-panels"><div className="quality-ring"><Check size={28}/><span>{t("VALIDATE")}</span></div><div className="mock-bars">{[76,91,59,84,68].map((n,i)=><div key={i}><span style={{width:n+'%'}}/></div>)}<small>{t("ILLUSTRATIVE QUALITY CHECKS")}</small></div></div><div className="assistant-box"><span><Sparkles size={15}/>{t(" DVIE ASSISTANT")}</span><p>{t("“Help me understand my data.”")}</p><div className="assistant-line"/><div className="assistant-line short"/></div></div></div><div className="mock-bottom"><span className="live-dot"/>{t(" Ingest ")}<span>→</span>{t(" Validate ")}<span>→</span>{t(" Understand")}</div></div><span className="visual-note">{t("ENGINEERED FOR TRUST. ENHANCED BY AI.")}</span></div></article>

  <div className="internship-missions"><h3>{t("PFA missions · JAAG Advisory")}</h3><ul>{['Analyze datasets and identify data quality issues.','Apply business rules and regulatory rules from the EBA taxonomy.','Combine data validation, reporting and the DVIE AI assistant within DataVex.'].map(mission=><li key={mission}>{t(mission)}</li>)}</ul></div>
  <article className="internship-card"><div className="internship-heading"><div><p className="eyebrow">{t("PFI INTERNSHIP / AUGUST 2025")}</p><h3>Expertise Data</h3><p>{t("Emotion Prediction")}</p></div><BrainCircuit size={32}/></div><h4>{t("Missions")}</h4><ul>{['Preprocess textual data for emotion prediction.','Apply Machine Learning techniques using Python.','Evaluate the prediction models.'].map(mission=><li key={mission}>{t(mission)}</li>)}</ul><div className="tags">{['Python','Machine Learning','NLP'].map(label=><span key={label}>{t(label)}</span>)}</div><button className="text-link" onClick={()=>setModal('Emotion Prediction')}>{t("View case study")} <ArrowUpRight size={15}/></button></article>
  </section>
  <section className="section projects reveal" id="projects"><div className="section-heading"><div><p className="eyebrow">{t("04 / ACADEMIC PROJECTS")}</p><h2>{t("Academic projects")}</h2></div><p>{t("Technical projects developed during my studies.")}</p></div>
  <div className="project-toolbar"><p>{t("Explore my academic work")}</p><div className="filters" aria-label={t("Filter projects")}>{['All projects','Data engineering','AI & ML'].map(f=><button key={f} className={filter===f?'active':''} aria-pressed={filter===f} onClick={()=>setFilter(f)}>{t(f)}</button>)}</div></div><div className="project-grid">{projects.filter(p=>p.title!=='Emotion Prediction' && (filter==='All projects'||p.category===filter)).map((p)=><article className="project-card" key={p.title}><button className={`project-art ${p.visual}`} onClick={()=>setModal(p.title)} aria-label={`${t("View case study")} : ${t(p.title)}`}><div className="art-grid"/><span className="art-source">{t(p.visual==='cnn'?'INPUT / PIXELS':'SOURCE / DATA')}</span><div className="art-diagram"><span><Database size={21}/></span><i/><span className="art-core"><p.icon size={32}/></span><i/><span><Layers size={21}/></span></div><span className="art-destination">{t(p.visual==='cnn'?'CLASSIFY / LEARN':'TRANSFORM / INSIGHT')}</span><ArrowUpRight className="art-arrow" size={20}/></button><div className="project-info"><span className="eyebrow">{t(p.category)}</span><h3>{t(p.title)}</h3><p>{t(p.desc)}</p><div className="tags">{p.tags.slice(0,3).map(label=><span key={label}>{t(label)}</span>)}</div><button className="text-link" onClick={()=>setModal(p.title)}>{t("View case study ")}<ArrowUpRight size={15}/></button></div></article>)}</div></section>
  <section className="section journey reveal" id="education"><div className="journey-intro"><p className="eyebrow">{t("05 / EDUCATION")}</p><h2>{t("Academic background")}</h2><p>{t("A foundation in science. A direction in data.")}<br/>{t("A journey shaped by building and collaborating.")}</p><div className="journey-stamp"><GitBranch size={28}/><span>{t("INFORMATION SYSTEMS")}<br/>& BIG DATA</span></div></div><div className="timeline">{[
  ['2024 — 2027','EDUCATION · IN PROGRESS','Engineering Cycle','ENSA Berrechid · Université Hassan Premier','Information Systems & Big Data'],
  ['2022 — 2024','EDUCATION','Preparatory Cycle','ENSA Berrechid · Université Hassan Premier','Preparatory studies for the engineering cycle.'],
  ['2021 — 2022','EDUCATION','Scientific Baccalaureate','Lycée Qualifiant Jaafar El Fassi El Fihri, Casablanca','Physics & Chemistry'],
  ].map(([date,type,title,place,desc],i)=><details key={title} className={i===0?'current':''} open={i<3}><summary><span className="timeline-dot"/><span className="timeline-meta">{t(date)}<span>{t(type)}</span></span><h3>{t(title)}<span>+</span></h3><span className="timeline-place">{t(place)}</span></summary><p>{t(desc)}</p></details>)}</div></section>
  <section className="section leadership reveal"><div className="section-heading"><div><p className="eyebrow">{t("06 / BEYOND THE TECHNICAL")}</p><h2>{t("Great things are ")}<span className="muted">{t("built together.")}</span></h2></div><p>{t("Leadership & activities")}</p></div><div className="leadership-grid"><article><span className="eyebrow">2024–2025 & 2025–2026</span><Network/><h3>R41 Robotics & AI</h3><h4>{t("Event Manager")}</h4><p>{t("Organizing technology events and conferences. Coordinating teams, logistics, communication, and collaboration with professional speakers and partners.")}</p></article><article><span className="eyebrow">2025–2026</span><GitBranch/><h3>Rotaract Club</h3><h4>{t("Event Manager")}</h4><p>{t("Bringing people and projects together through event organization, team coordination, communication, collaboration, and project supervision.")}</p></article></div></section>
  <section className="section skills reveal" id="skills"><div className="section-heading"><div><p className="eyebrow">{t("07 / MY TOOLKIT")}</p><h2>{t("The tools behind ")}<span className="muted">{t("the thinking.")}</span></h2></div><p>{t("A growing ecosystem of technologies,")}<br/>{t("applied through projects and exploration.")}</p></div><div className="skills-layout"><div className="skill-tabs" role="tablist" aria-label={t("Skill categories")} aria-orientation="vertical">{skills.map((s,i)=><button role="tab" id={`skill-tab-${i}`} aria-controls="skill-panel" aria-selected={skill===i} tabIndex={skill===i?0:-1} onKeyDown={e=>{if(['ArrowDown','ArrowUp','Home','End'].includes(e.key)){e.preventDefault();const next=e.key==='Home'?0:e.key==='End'?3:(i+(e.key==='ArrowDown'?1:3))%4;setSkill(next);document.getElementById(`skill-tab-${next}`)?.focus();}}} onClick={()=>setSkill(i)} className={skill===i?'active':''} key={s.name}><s.icon size={20}/>{t(s.name)}<ArrowUpRight size={16}/></button>)}</div><div className="skill-panel" id="skill-panel" role="tabpanel" aria-labelledby={`skill-tab-${skill}`} tabIndex={0}><span className="eyebrow">{t(skills[skill].name)}{t(" / TOOLKIT")}</span><div className="skill-tags">{skills[skill].items.map(label=><span key={label}><span className="accent">◇</span>{t(label)}</span>)}</div></div></div><div className="languages"><span className="eyebrow">{t("LANGUAGES I CONNECT IN")}</span>{[['Arabic','Native'],['French','Fluent'],['English','Fluent'],['Spanish','Beginner']].map(([l,v])=><div key={l}>{t(l)}<span>{t(v)}</span></div>)}</div></section>
  <section className="contact section reveal" id="contact"><span className="availability"><span className="live-dot"/>{t(" Open to internship opportunities")}</span><p className="eyebrow">{t("08 / LET’S MAKE SOMETHING MATTER")}</p><h2>{t("Let’s build intelligent")}<br/><span>{t("data solutions.")}</span></h2><p>{t("Have an opportunity, a project, or an idea?")}<br/>{t("I’d love to start a conversation.")}</p><div className="contact-actions"><a className="email-link" href="mailto:asmaa02talal@gmail.com">asmaa02talal@gmail.com <ArrowUpRight/></a><button className="copy-button" aria-label={t("Copy email address")} onClick={async()=>{try{await navigator.clipboard.writeText('asmaa02talal@gmail.com');setCopied(true);setTimeout(()=>setCopied(false),2500);}catch{setModal('email');}}}>{copied?<Check size={18}/>:<Copy size={18}/>}</button><span className="sr-only" role="status">{copied?t('Email address copied'):''}</span></div><div className="contact-links"><span><MapPin size={15}/>{t(" Casablanca, Morocco")}</span><a href="tel:+212774968486">+212 774968486</a><button onClick={cv}><Download size={15}/>{t(" Download CV")}</button></div></section></main><footer><a className="brand" href="#home">at<span>.</span></a><p>© {new Date().getFullYear()} Asmaa Talal <span>·</span>{t(" Built with curiosity & intention.")}</p><a href="#home">{t("Back to top ↑")}</a></footer>
  <dialog ref={dialog} onCancel={()=>setModal(null)} onClick={e=>{if(e.target===dialog.current)setModal(null);}} aria-labelledby="modal-title"><div className="modal-inner"><button className="modal-close" onClick={()=>setModal(null)} aria-label={t("Close dialog")}><X/></button>{modal==='cv'?<><p className="eyebrow">CURRICULUM VITAE</p><h2 id="modal-title">{t("Let’s get in touch.")}</h2><p>{t("The downloadable CV will be added soon. Please email me to request a copy.")}</p><a className="button primary" href="mailto:asmaa02talal@gmail.com?subject=CV%20request"><Mail size={17}/>{t(" Request my CV")}</a></>:modal==='email'?<><h2 id="modal-title">{t("Email Asmaa")}</h2><a href="mailto:asmaa02talal@gmail.com">asmaa02talal@gmail.com</a></>:modal==='DataVex'?<><p className="eyebrow">{t("FEATURED CASE STUDY / 2026 PFA")}</p><h2 id="modal-title">DataVex<span className="accent">.</span></h2><p className="modal-subtitle">{t("AI-Powered Data Quality & Data Governance Platform")}</p><span className="project-completed"><Check size={13}/>{t("Completed project")}</span><div className="case-grid">{[
 ['The problem','Inconsistent records and complex business rules make it difficult to understand whether data can be trusted.'],['The objective','Design an intelligent platform to analyze datasets, compare databases, check business and EBA taxonomy regulatory rules, and generate verification reports.'],['Regulatory rules · EBA taxonomy','DataVex includes regulatory rules from the EBA taxonomy alongside business rules in its data quality checks.'],['Internship context','PFA internship at JAAG Advisory.'],['Architecture','React, Vite and Material UI form the interface. A FastAPI REST API connects Python, Pandas and SQLAlchemy to SQL Server, with JWT authentication in the architecture.'],['Data quality','Dataset profiling, inconsistency detection, executable business rules, dataset comparison, quality scoring and automated reporting.'],['AI component · DVIE','An intelligent assistant designed to explain quality issues and translate natural-language business rules into executable checks. Example: “Generate a rule to verify email addresses.”'],['Technical challenges','Design considerations include mapping natural-language requirements to reliable checks, comparing heterogeneous data, and explaining validation findings clearly.'],['Results & status','Completed PFA project at JAAG Advisory. The portfolio visualization illustrates the platform concept; measured results are not presented here.'],['My contribution','DataVex is my PFA project at JAAG Advisory, focused on data engineering, data quality, EBA taxonomy regulatory rules and AI.']
 ].map(([title,body])=><div key={title}><h3>{t(title)}</h3><p>{t(body)}</p></div>)}</div><div className="tags">{['Python','FastAPI','SQL Server','Pandas','SQLAlchemy','React','Vite','Material UI','REST API','JWT','NLP','LLM / AI Agent'].map(label=><span key={label}>{t(label)}</span>)}</div></>:<><p className="eyebrow">{modal==='Emotion Prediction'?t("PFI INTERNSHIP / EXPERTISE DATA"):t("ACADEMIC PROJECT / ")}{modal!=='Emotion Prediction' && t(projects.find(p=>p.title===modal)?.category)}</p><h2 id="modal-title">{t(modal ?? undefined)}</h2><p>{t(projects.find(p=>p.title===modal)?.detail)}</p><div className="tags">{projects.find(p=>p.title===modal)?.tags.map(label=><span key={label}>{t(label)}</span>)}</div><a className="button secondary" href="mailto:asmaa02talal@gmail.com?subject=Let%E2%80%99s%20talk%20about%20your%20project">{t("Discuss this project ")}<ArrowUpRight size={16}/></a></>}</div></dialog></>;
}
createRoot(document.getElementById('root')!).render(<React.StrictMode><PreferencesProvider><App/></PreferencesProvider></React.StrictMode>);
